name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Cache MkDocs dependencies
        run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Install docs dependencies
        run: pip install -r requirements-docs.txt

      - name: Build docs (strict)
        run: python -m mkdocs build --strict

      - name: Deploy docs
        run: python -m mkdocs gh-deploy --force
